### ISSUE TITLE
update hiddify-panel error

### ISSUE THREAD

**Issue by akrhin** [hiddify/Hiddify-Manager#3391] opened 2023-11-08 10:35 UTC
I tried to update the panel via the web and via bash, the result is below. How to fix? Hiddify 8.6.11

```
common/utils.sh: line 31: cd: /opt/hiddify-server/hiddify-panel: No such file or directory
/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py:851: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/__main__.py", line 13, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 407, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/cli.py", line 50, in all_configs
    valid_users = [u.to_dict() for u in User.query.filter((User.usage_limit_GB > User.current_usage_GB)).all() if is_user_active(u)]
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/cli.py", line 50, in <listcomp>
    valid_users = [u.to_dict() for u in User.query.filter((User.usage_limit_GB > User.current_usage_GB)).all() if is_user_active(u)]
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/user.py", line 148, in to_dict
    'added_by_uuid': d.admin.uuid,
AttributeError: 'NoneType' object has no attribute 'uuid'
parse error: Invalid numeric literal at line 1, column 11
cat: /opt/hiddify-server/VERSION: No such file or directory
Creating a backup ...


XXX
5
Checking for Update...
Hiddify Panel
XXX
Error: Option '-v' requires an argument.
Unknown package mode: 
```

**Comment by ashkanzayeromali** [comment] 2023-11-08 11:16
i have this exact problem too

**Comment by sadjad1011001** [comment] 2023-11-08 14:50
I have this problem too, I think the hiddibot made some error on users database!

**Comment by younes2513** [comment] 2023-11-08 17:16
i have this exact problem too

**Comment by sadjad1011001** [comment] 2023-11-09 11:49
> i have this exact problem too

did you set up the hiddibot on your server too?

**Comment by ashkanzayeromali** [comment] 2023-11-09 12:17
> > i have this exact problem too
> 
> did you set up the hiddibot on your server too?
yes i did

**Comment by pjrobertson** [comment] 2023-11-10 06:04
This seems to be a duplicate of #3362

I have given instructions on what I did to fix this there.

**Comment by sadjad1011001** [comment] 2023-11-12 09:47
@hiddify-com @HiddifyOfficial  No ones wants to resolve such important update issue!?

**Comment by sadjad1011001** [comment] 2023-11-22 13:51
hello is any one there?

**Comment by lymanjre** [comment] 2024-01-26 12:59
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.

**Closed by lymanjre** 2024-01-26 12:59 UTC

**Comment by nimadn** [comment] 2024-02-08 11:06
I could solve it after downgrading via Advanced menu in the Terminal. After downgrading from development to standard ( Although I was already on standard mode) it allowed me to update again flawlessly.
