### ISSUE TITLE
[BUG] RU routing for sing-box

### ISSUE THREAD

**Issue by legiz-ru** [hiddify/Hiddify-Manager#4392] opened 2024-08-06 16:25 UTC
**Describe the bug**
Not start singbox config with RU routing

**To Reproduce**
1. russia country in general settings
![image](https://github.com/user-attachments/assets/5f1cbef6-389e-4a30-bd66-9d8a6597b7f3)

2. Copy Full Singbox from All Configurations link
3. Paste to sing-box app, run this config with error
![image](https://github.com/user-attachments/assets/1a0ebd15-7b67-44ef-be65-6bb647b360f4)

**Expected behavior**

**Device and  server**

 - Hiddify Panel: 10.70.4
 - Device: Galaxy S23
 - OS: Android 14
 - App: sing-box for android
 - Version: 1.10.0-alpha.25

**No rule_set link in config:**

![image](https://github.com/user-attachments/assets/39ae16ad-97be-422d-a520-1932c33dc1e0)

**Additional context**

**Comment by litoosh13** [comment] 2024-10-03 18:58
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager

**Comment by litoosh13** [comment] 2024-10-24 15:19
please if you have this problem provide more info

**Comment by lymanjre** [comment] 2024-10-25 05:05
The issue is merged. thx for contribution

**Closed by lymanjre** 2024-10-25 05:05 UTC
